### ISSUE TITLE
issue when sending curl command through load-balancer with x-forwarded-for header

### ISSUE THREAD

**Issue by roeilichter** [wizzardo/webery#5]
when sending curl command with param, the request method and request parameter are concatenated to form the METHOD.

what could be the issue?

**Comment by wizzardo** [comment]
sounds really strange, can you provide more info? example?

**Comment by roeilichter** [comment]
Hi,
im not sure if its related to X-Forwarded-For , but when i tried to send
curl command through load balancer (in AWS) that X-forwarded-for is not
include in the header - and issue is not happens.

the issue is that in trying to send the following curl command: "curl -v
--data-urlencode
"param1=eHUoPLvEMQOR9k3du6gTZGmg+AhLubI9qNrerUCDSarxrJTBSgiyCqWMOGz/LyTeEK3bdelIiJ1+NLj9tas4GhfepxPKaLB/9ZT8f9EvDxXzy51EjM6sKwAhg2qywKWiXFqwgKVV9rvyrKM9QeQmI77hjf2gHzcJvlK3wSpNZoex+0VsMk+pclS8A5/NjY8gTwH7GIj31gMb3fRopt8WOaMlDEQHloEKz+mVmn4Q0fmHMvTFklnxJF+Sv1RT4A9YGAE7jEjjOvAoRNoYWzZYYTSWPRObX5PZ43h2TnAm9OUcS4OYpTC1TcqgKoWe7jYto2WOZk+XIXgPPSbtkugq/w=="
--header "Content-Type: application/x-www-form-urlencoded; charset=utf-8""
and when im sending it through load balancer with X-Forwarded-For header,
then sometimes the request is being failed due to that the request method
and request parameter are concatenated to form the METHOD.
means that - the method that should be "POST" , is become: "
param1=eHUoPLvEMQOR9k3du6gTZGmg%2BAhLubI9qNrerUCDSarxrJTBSgiyCqWMOGz%2FLyTeEK3bdelIiJ1%2BNLj9tas4GhfepxPKaLB%2F9ZT8f9EvDxXzy51EjM6sKwAhg2qywKWiXFqwgKVV9rvyrKM9QeQmI77hjf2gHzcJvlK3wSpNZoex%2B0VsMk%2BpclS8A5%2FNjY8gTwH7GIj31gMb3fRopt8WOaMlDEQHloEKz%2BmVmn4Q0fmHMvTFklnxJF%2BSv1RT4A9YGAE7jEjjOvAoRNoYWzZYYTSWPRObX5PZ43h2TnAm9OUcS4OYpTC1TcqgKoWe7jYto2WOZk%2BXIXgPPSbtkugq%2Fw%3D%3DPOST"

**Comment by wizzardo** [comment]
ok, thanks for provided description, do you use latest snapshot or tag 0.3?

**Comment by roeilichter** [comment]
not sure.... how do i check it?
i just did clone to the project few months ago

**Comment by wizzardo** [comment]
I wasn't able to reproduce the issue (tried to spin up an ec2 instance with load-balancer), but I pushed some commits, please pull the changes to be sure that you have the latest version

**Comment by roeilichter** [comment]
does the load balancer that you used - i using X-forwarded-for header?

**Comment by wizzardo** [comment]
yes, and some others, you can try it on http://testapp-env.eba-xa72xtmd.eu-central-1.elasticbeanstalk.com/post I will kill it tomorrow

**Comment by wizzardo** [comment]
I've took a look again and managed to reproduce the issue without the latest changes, now it's fixed
