### ISSUE TITLE
Secure sessions

### ISSUE THREAD

**Issue by joelmo** [wizzardo/webery#6]
I would like to be able to replace the session ID and have more control of how it is generated.
My suggestion is to extend the Session object with a replaceId method so you can do this: `request.session().replaceId(generateSecureHash())`.

Current method uses MD5 which have proven to be vulnurable. It may be easier to spoof a session when MD5 is used. Another concern is that only 32**2 different session IDs are generated. This is probably fine when secure sessions aren't needed.

**Comment by wizzardo** [comment]
Good point! I added `SessionIdGenerator` interface and moved md5-implementation to separate class, so you can set your own SessionIdGenerator by `Session.setSessionIdGenerator(new SecureSessionIdGenerator())`

**Comment by joelmo** [comment]
Very good. Thanks!
